version: '3.5'

services:
  php:
    image: '127.0.0.1:5000/ashledombos/spip-php:latest'
    build: './fpm'
    depends_on:
      - mariadb
    networks:
      - backend
    volumes:
      - spip-data:/var/www/html
    configs:
      - vhost_spip.conf
  apache:
    image: '127.0.0.1:5000/ashledombos/spip-web:latest'
    build: './web'
    depends_on:
      - php
      - mariadb
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - spip-data:/var/www/html
    configs:
      - vhost_spip.conf
    labels:
      - "traefik.frontend.rule=Host:spip.docker.localhost"
  mariadb:
    image: yobasystems/alpine-mariadb:latest
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
  redis:
    image: "redis:alpine"

#  reverse-proxy:
#    image: traefik # The official Traefik docker image
#    command: --api --docker # Enables the web UI and tells Træfik to listen to docker
#    ports:
#      - "80:80"     # The HTTP port
#      - "8080:8080" # The Web UI (enabled by --api)
#    networks:
#      - frontend
#      - backend
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events     
      
volumes:
   spip-data:

networks:
   frontend:
   backend:

configs:
   vhost_spip.conf:
    file: ./vhost_spip.conf
