version: '3.5'
# for local development, with local registry

services:
  apache:
    image: '127.0.0.1:5000/ashledombos/spip-web:latest'
    build: ../${SPIP_VERSION}/web
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8081:80"
    volumes:
      - ./spip-core:/var/www/html/core
      - ./spip-data:/var/www/html/data
  php:
    image: '127.0.0.1:5000/ashledombos/spip-fpm:latest'
    build: ../${SPIP_VERSION}/fpm
    depends_on:
      - mysql
    networks:
      - backend
    volumes:
      - spip-core:/var/www/html/core
      - spip-data:/var/www/html/data
    environment:
      - SPIP_DB_SERVER=mysql
      - SPIP_DB_HOST=mysql
      - SPIP_DB_LOGIN=spip
      - SPIP_DB_PASS=spip
      - SPIP_DB_PREFIX=spip
      - SPIP_ADMIN_NAME=Admin
      - SPIP_ADMIN_LOGIN=admin
      - SPIP_ADMIN_EMAIL=spip@spip
      - SPIP_ADMIN_PASS=adminadmin
      - PHP_MAX_EXECUTION_TIME=60
      - PHP_MEMORY_LIMIT=256M
      - PHP_POST_MAX_SIZE=40M
      - PHP_UPLOAD_MAX_FILESIZE=32M
      - PHP_TIMEZONE=America/Guadeloupe
  mysql:
    image: mariadb:10.3
    networks:
      - backend
    volumes:
      - ./spip-db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=spip
      - MYSQL_USER=spip
      - MYSQL_PASSWORD=spip
      - MYSQL_ROOT_PASSWORD=SuperPassword      
networks:
   frontend:
   backend:
