
version: '3.5'
# Using træfik as reverse proxy, no need to expose apache service on port 80

services:
  apache:
    image: 'ashledombos/spip-web:3.2'
    depends_on:
      - php
      - mysql
    networks:
      - web
      - default
    volumes:
      - ./spip-core:/var/www/html/core
      - ./spip-data:/var/www/html/data
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:spip-url.com"
  php:
    image: 'ashledombos/spip-fpm:3.2'
    depends_on:
      - mysql
    volumes:
      - ./spip-core:/var/www/html/core
      - ./spip-data:/var/www/html/data
    environment:
      - SPIP_DB_SERVER=mysql
      - SPIP_DB_HOST=mysql
      - SPIP_DB_LOGIN=spip
      - SPIP_DB_PASS=spip
      - SPIP_DB_PREFIX=spip
      - SPIP_ADMIN_NAME=Admin
      - SPIP_ADMIN_LOGIN=admin
      - SPIP_ADMIN_EMAIL=spip@spip
      - SPIP_ADMIN_PASS=adminadmin
      - PHP_MAX_EXECUTION_TIME=60
      - PHP_MEMORY_LIMIT=256M
      - PHP_POST_MAX_SIZE=40M
      - PHP_UPLOAD_MAX_FILESIZE=32M
      - PHP_TIMEZONE=America/Guadeloupe
  mysql:
    image: mariadb:10.3
    volumes:
      - ./spip-db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=spip
      - MYSQL_USER=spip
      - MYSQL_PASSWORD=spip
      - MYSQL_ROOT_PASSWORD=SuperPassword
networks:
    web:
        external: true
