version: '3.5'
# Please set environment variables in .env file

services:
  php:
    image: '127.0.0.1:5000/ashledombos/spip-fpm:latest'
    build: ../${SPIP_VERSION}/fpm
    depends_on:
      - mysql
    networks:
      - backend
    volumes:
      - spip-core:/var/www/html/core
      - spip-data:/var/www/html/data
    environment:
      - SPIP_DB_SERVER=mysql
      - SPIP_DB_HOST=mysql
      - SPIP_DB_LOGIN=${SPIP_DB_LOGIN}
      - SPIP_DB_PASS=${SPIP_DB_PASS}
      - SPIP_DB_PREFIX=${SPIP_DB_PREFIX}
      - SPIP_ADMIN_NAME=${SPIP_ADMIN_NAME}
      - SPIP_ADMIN_LOGIN=${SPIP_ADMIN_LOGIN}
      - SPIP_ADMIN_EMAIL=${SPIP_ADMIN_EMAIL}
      - SPIP_ADMIN_PASS=${SPIP_ADMIN_PASS}
      - PHP_MAX_EXECUTION_TIME=${PHP_MAX_EXECUTION_TIME}
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT}
      - PHP_POST_MAX_SIZE=${PHP_POST_MAX_SIZE}
      - PHP_UPLOAD_MAX_FILESIZE=${PHP_UPLOAD_MAX_FILESIZE}
      - PHP_TIMEZONE=${PHP_TIMEZONE}
  apache:
    image: '127.0.0.1:5000/ashledombos/spip-web:latest'
    build: ../${SPIP_VERSION}/web
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8081:80"
    volumes:
      - ./spip-core:/var/www/html/core
      - ./spip-data:/var/www/html/data
    labels:
      - "traefik.frontend.rule=Host:spip.docker.localhost"
  mysql:
    image: yobasystems/alpine-mariadb:latest
    networks:
      - backend
    volumes:
      - ./spip-db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${SPIP_DB_NAME}
      - MYSQL_USER=${SPIP_DB_LOGIN}
      - MYSQL_PASSWORD=${SPIP_DB_PASS}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  redis:
    image: "redis:alpine" 
      
networks:
   frontend:
   backend:
